### ISSUE TITLE
Audio behaviour when dependencies break

### ISSUE THREAD

**Issue by ksandom** [ksandom/handWavey#66]
## The problem

When dependencies break, the audio dies. This happens in its own thread, so doesn't break anything other than the audio.

It looks like this:

```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
        at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:484)
        at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:115)
        at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:142)
        at audio.SimplePlayer.playSound(SimplePlayer.java:56)
        at audio.BackgroundSound.run(BackgroundSound.java:32)
```

I haven't dug into what the breakage is, but this is the second time it has happened. The first was when the migration to pipewire from pulseaudio happened. 

I'm expecting the problem to disappear when I apply updates later today, and I don't have time to dive deeper into it for now.

Some other applications are affected (including VirtualBox), but not all.

## Research

I've found a fair bit of discussion on the topic. **Everything** talks about this this being a combination of windows + specific hardware problem. I'm having this on Linux.

## Goal of the ticket

* Track that it's a known issue.
* Consider how to handle the problem in the future? Eg
  * Leave it and wait for the dependency to be fixed.
  * Catch the exception and place a debug entry in the terminal output.
  * Rewrite the audio functionality using another framework.

**Comment by ksandom** [comment]
Yay, it took a bit longer than I expected. But what ever was broken upstream, is fixed now.
